### NumPy
Use for making arrays and matrices

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b=np.array([ [2.3,4.5,6.7],[1.3,4.5,6.7] ])
b

array([[2.3, 4.5, 6.7],
       [1.3, 4.5, 6.7]])

In [5]:
b.ndim

2

In [6]:
a.ndim

1

In [10]:
a.shape
a.dtype

dtype('int32')

In [ ]:
b.shape

In [ ]:
x=a.reshape(2,2)
x

In [8]:
np.min(a)

1

In [7]:
np.random.rand(2,3)

array([[0.06862967, 0.62800782, 0.43121778],
       [0.09665977, 0.82593125, 0.64657423]])